version: '3'

# docker-compose up
# docker rm $(docker ps -a -q) && docker volume prune -f

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "57ry4ardpa77"
      MYSQL_DATABASE: forum
    ports:
      - '3306:3306'
    volumes:
      - './internal/storage/mysqlStorage/_sql/:/docker-entrypoint-initdb.d/'

  redis:
    image: 'redis'
    ports:
      - '6379:6379'

  mongodb:
    image: 'mongo:5'
    ports:
      - '27017-27019:27017-27019'

  goapp:
    image: 'golang:1.21.0'
    volumes:
      - './:/forum'
    working_dir: '/forum'
    command: bash -c "go get ./... && go run ./cmd/forum/main.go"
    ports:
      - '8080:8080'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8090:8080'
